# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test application

on:
  push:
    branches: [ "main", "dev", "test/*", "test-*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        python -m pip install poetry==1.7.0
    - name: Install dependencies with poetry
      run: |
        python -m poetry install
    - name: Test with pytest
      run: |
        python -m poetry run python -m pytest
